Created Basic tools to build and run images based on current directory with "Dockerfile"

diff --git a/bin/container b/bin/container
--- a/bin/container
+++ b/bin/container
@@ -1,13 +1,15 @@
 #!/bin/sh
 
 CURRENT_DIR=$(pwd)
+REF_NAME=$(basename $CURRENT_DIR)
+DOCKERFILE="${CURRENT_DIR}/Dockerfile"
 TOOLS_DIR=$(dirname $(readlink -m $0))
 COMMAND=$1
 E_OUT='>&2'
 
 ### Command selection
 if [ $# -lt 1 ] || [ ! "${COMMAND}" ]; then
-    echo Please select command. >&2
+    echo "! Please select command." >&2
     exit 1;
 fi
 
@@ -15,15 +17,20 @@ shift 1
 
 ### Docker installation?
 if ! which docker > /dev/null; then
-    echo No docker-engine installed. >&2
+    echo "! No docker-engine installed." >&2
     exit 2
 fi
 
 if ! docker ps > /dev/null; then
-    echo docker-engine is not properly installed or docker daemon has not started. >&2
-    exit 3
+    echo "! docker-engine is not properly installed or docker daemon has not started." >&2
+    exit 20
 fi
 
+### Dockerfile check
+if [ ! -f "${DOCKERFILE}" ] || [ ! -r "${DOCKERFILE}" ]; then
+    echo "! Dockerfile do no exist in this directory." >&2
+    exit 21
+fi
 
 ### Execute command
 SUBCOMMAND_DIR="${TOOLS_DIR}/container_sub"
@@ -34,10 +41,13 @@ if [ -x "${COMMAND_DIR}" ]; then
     export TOOLS_DIR
     export CURRENT_DIR
     export COMMAND
+    export DOCKERFILE
+    export REF_NAME
     export SUBCOMMAND_DIR
-    "${COMMAND_DIR}" $*
-    exit $?
+    eval ${COMMAND_DIR} $* || exit $?
+    exit 0
 fi
 
-echo "Command ${COMMAND} not found" >&2
+echo "! Command ${COMMAND} not found" >&2
+
 exit 4
diff --git a/bin/container_sub/build b/bin/container_sub/build
--- a/bin/container_sub/build
+++ b/bin/container_sub/build
@@ -1,7 +1,13 @@
 #/bin/sh
 
-. "${SUBCOMMAND_DIR}/dockerfile_check.sh" $*
-. "${SUBCOMMAND_DIR}/command_ref_check.sh" $*
 
-echo "tools: ${TOOLS_DIR}"
-echo "build options: ${*}"
+echo "* Building image... ${REF_NAME}"
+echo 
+if ! docker build -t ${REF_NAME} .; then
+    echo "! Unable to build Image ${REF_NAME}" >&2
+    exit 30
+fi
+
+echo "* Built image: ${REF_NAME}"
+
+exit 0
diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,27 +8,35 @@ if [ ! -d "${HOME_BIN}" ]; then
     mkdir ${HOME_BIN}
 fi
 
+if [ ! -w "${HOME_BIN}" ]; then
+    echo "You have no write permission to ${HOME_BIN}" >&2
+    exit 1
+fi
+
 cd "${TOOLS_DIR}"
-for FILE in $(find *); do
-    
-    if [ ! -r "${FILE}" ]; then
-        echo "Unable to read file/directory ${FILE}" >&2
-        cd "${RESTORE_DIR}"
-        exit 1
+chmod +x $(find . -type f | grep -v '.sh')
+
+for FILE in $(ls -1); do
+
+    FULL_PATH="${TOOLS_DIR}/${FILE}"
+
+    if [ -d "${FULL_PATH}" ]; then
+        if ! cp -Rf "${FULL_PATH}" "${HOME_BIN}"; then
+            echo "There were errors copying files ${FULL_PATH} to ${HOME_BIN}" >&2
+            exit 2
+        fi
+    elif [ -f "${FULL_PATH}" ]; then
+        if ! cp "${FULL_PATH}" "${HOME_BIN}"; then
+            echo "There were errors copying files ${FULL_PATH} to ${HOME_BIN}" >&2
+            exit 2
+        fi
     fi
-    
-    TARGET="${HOME_BIN}/${FILE}"
-    if [ -e "${TARGET}" ]; then
-        rm -Rf "${TARGET}"
-    fi
-        
-    if [ -d "${FILE}" ]; then
-        mkdir "${TARGET}"
-        
-    else
-        cp "${FILE}" $(dirname "${TARGET}")
-    fi
+
 done
+
+cd "${HOME_BIN}"
+
+chmod +x $(find . -type f | grep -v '.sh')
 
 cd "${RESTORE_DIR}"
 exit 0
